# Generated by Django 2.2 on 2020-01-31 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upscapp', '0004_auto_20200130_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='contenttypes.ContentType'),
        ),
    ]
