# Generated by Django 2.2 on 2020-01-31 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upscapp', '0007_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
